language: python
osx_image: xcode8.2
python:
  - "2.7"
before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 7 # for Node v7
  - node --version
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
# Run the iOS test
script: 
-- xcode-select --print-path
- npm install -g appium@1.6.3 --no-shrinkwrap
- appium &
- sleep 30
- cd sample-code/examples/python && python ios_simple.py
