sudo: required
language: objective-c 
osx_image: xcode8.2
env:
- ANDROID_HOME=/usr/local/share/android-sdk PATH=$PATH:$ANDROID_HOME ANDROID_SDK_ROOT=/usr/local/share/android-sdk
before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 7 # for Node v7
  - brew tap
  - brew tap caskroom/cask
  - brew cask install --appdir=~/Applications intel-haxm
  - brew cask install android-sdk
  - brew cask install android-platform-tools
# command to install dependencies
install: "sudo pip install -r requirements.txt"
# command to run tests
# Run the iOS test
script: 
- echo $PATH
- sdkmanager "platforms;android-22"
- sdkmanager "system-images;android-22;google_apis;x86"
- avdmanager create avd --package 'system-images;android-22;google_apis;x86' --name Nexus_6 --tag "google_apis" -d "Nexus 6" -c 100M 
- avdmanager list avd 
- ls $ANDROID_HOME
- $ANDROID_HOME/emulator/emulator -avd  Nexus_6 -skindir $ANDROID_HOME/skins -skin nexus_6 -memory 1024 &
- sleep 30
- echo $HOME
- python --version 
- npm install -g appium@1.6.3 --no-shrinkwrap
- appium &
- sleep 30
- adb devices
- cd sample-code/examples/python && python ios_simple.py
- python android_simple.py
