language: android
before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 7 # for Node v7
# command to install dependencies
install: "sudo pip install -r requirements.txt"
# command to run tests
# Run the test
script: 
- $ANDROID_HOME/tools/android list targets
- $ANDROID_HOME/tools/android create avd -n Nexus_6 -t 8 
#- $ANDROID_HOME/tools/bin/avdmanager list avd 
- ls $ANDROID_HOME/tools
- $ANDROID_HOME/emulator/emulator -avd  Nexus_6 -skindir $ANDROID_HOME/skins -skin nexus_6 -memory 1024 -no-window -no-audio -no-boot-anim -verbose &
- sleep 30
- echo $HOME
- python --version 
- npm install -g appium@1.6.3 --no-shrinkwrap
- appium &
- sleep 30
- adb devices
- cd sample-code/examples/python && python android_simple.py
