sudo: required
language: python
osx_image: xcode8.2
node_js:
  - "7"
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
# Run the iOS test
script: 
- npm install -g appium@1.6.3 --no-shrinkwrap
- appium &
- cd sample-code/examples/python && python ios_simple.py
