language: python
osx_image: xcode8.2
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
# Run the iOS test
script: 
- cd sample-code/examples/python && python ios_simple.py
