sudo: required
language: objective-c 
osx_image: xcode8.2
env:
- ANDROID_HOME=/usr/local/share/android-sdk PATH=$PATH:$ANDROID_HOME ANDROID_SDK_ROOT=/usr/local/share/android-sdk
before_install:
  - brew tap
  - brew tap caskroom/cask
  - brew cask install android-sdk
  - brew cask install android-platform-tools
  - echo y | sdkmanager "platforms;android-22"
  - echo y | sdkmanager 'system-images;android-22;default;armeabi-v7a'
  - echo y | sdkmanager "system-images;android-22;google_apis;armeabi-v7a"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  #- avdmanager create avd --package 'system-images;android-22;google_apis;armeabi-v7a' --name Nexus_6 --tag "google_apis" -d "Nexus 6" -c 100M 
  # Start emulator early since it takes a long time to boot
  #- $ANDROID_HOME/emulator/emulator -avd  Nexus_6 -skindir $ANDROID_HOME/skins -skin nexus_6 -memory 1024 -no-window -no-audio -no-boot-anim -verbose &
  - $ANDROID_HOME/tools/bin/avdmanager create avd --force --name test --package 'system-images;android-22;default;armeabi-v7a' --abi armeabi-v7a --device 'Nexus 4' --sdcard 128M
  - $ANDROID_HOME/emulator/emulator -avd test -skin 768x1280 -no-audio -no-window -verbose &
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 7 # for Node v7
  - npm install -g appium@1.6.3 --no-shrinkwrap
# command to install dependencies
install: "sudo pip install -r requirements.txt"
# command to run tests
# Run the iOS test
script: 
- appium &
- sleep 30
- cd sample-code/examples/python 
#- python ios_simple.py
- while [ "`adb shell getprop sys.boot_completed | tr -d '\r' `" != "1" ] ; do echo "Waiting for device" && sleep 1; done
- adb shell input keyevent 82 &
- adb devices
- python android_simple.py
