language: android
  components:
    # The SDK version used to compile your project
    - android-22
    - sys-img-armeabi-v7a-android-22
before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 7 # for Node v7
# command to install dependencies
install: "sudo pip install -r requirements.txt"
# command to run tests
# Run the test
script: 
- $ANDROID_HOME/tools/android list targets
#- $ANDROID_HOME/tools/bin/avdmanager list avd 
- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
- ls $ANDROID_HOME/tools
- python --version 
- npm install -g appium@1.6.3 --no-shrinkwrap
- appium &
- sleep 30
- adb devices
- cd sample-code/examples/python && python android_simple.py
